### ISSUE TITLE
suggestion: website

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#11] opened 2015-05-24 18:06 UTC
You can create a website using GitHub pages easily.

https://pages.github.com/

If you want to generate it using existing templates there is the generator in the settings:
https://github.com/Maikuolan/phpMussel/settings called **Automatic page generator**

Or you use custom HTML using **Custom and Jekyll-based sites**

Then you have a branch called gh-pages where the code for the website belongs.
If you need a domain (I also have some free domains left) you can easily point the domain to the GitHub page with special DNS settings

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

Pretty easy, isn't it?
So you don't need your own hosting for this and you can optionally use your own domains.

**Comment by Maikuolan** [comment] 2015-06-09 16:33
Definitely something to look into.

I've had a few people ask me about setting up a website for phpMussel before and it's something that's been on the to-do list for a while, but that I hadn't yet gotten around to doing.

Looking into it; I'll experiment a little with it tonight to see how it all works.

**Comment by Maikuolan** [comment] 2015-06-27 15:25
(( ..18 days later. ))

Leaving the "Attention Required" label here, to remind myself that I still need to get this sorted out.

**Comment by Maikuolan** [comment] 2016-03-20 17:35
Because we've had the _GitHub pages_ page for phpMussel for a while now (and this seems to be adequately doing the job as intended), which - although not tied to a domain name of its own - technically does qualify as a website, I think I'll close this issue for now.

We don't have a need for a domain name of our own at this time, but we should reopen this issue again if we decide to look into this in the future.

(We should also consider adopting use of a GitHub pages page for phpMussel via our recently created GitHub organisation for phpMussel, after we've finished preparing v1.0.0).

**Closed as completed** 2016-03-20 17:37 UTC
Labels: Suggestion, Implemented

**Comment by DanielRuf** [comment] 2016-03-20 18:13
Adding a domain name then should be quite easy (CNAME file) see https://github.com/Maikuolan/phpMussel/issues/11#issue-80227684

**Comment by Maikuolan** [comment] 2016-03-20 18:24
:+1: :-)
