### ISSUE TITLE
phpMussel is not scanning files as expected!!!

### ISSUE THREAD

**Issue by wajdijurry** [phpMussel/phpMussel#126] opened 2017-03-30 22:40 UTC
I have installed phpMussel on my server, it does not scanning any files at all!! Any infected file is uploaded to the server although i pass it through phpMussel. Where is the problem exactly of why phpMussel AV not scanning any file ?

**Comment by DanielRuf** [comment] 2017-03-30 22:50
How did you install it?
Do you use the .htaccess file and the `auto_prepend_file` rule?

Please use the issue template.

Do you use FastCGI / CGI or module for PHP?
Is your .htaccess file even processed by your server?
Try adding
```
Deny from all
```
to your .htaccess

**Comment by wajdijurry** [comment] 2017-03-30 22:54
I am using include method in PHP.
Also, i am using phpMussel as module for PHP, not CGI.
The htaccess file is processed by Apache server. I don't know why phpMussel could not scan the infected files.

**Comment by DanielRuf** [comment] 2017-03-30 22:56
Please try using the `auto_prepend_file` solution fro the documentation.

**Comment by DanielRuf** [comment] 2017-03-30 22:57
> If you're using an Apache webserver and if you have access to php.ini, you can use the auto_prepend_file directive to prepend phpMussel whenever any PHP request is made. Something like:
> 
> auto_prepend_file = "/user_name/public_html/phpmussel/loader.php"
> 
> Or this in the .htaccess file:
> 
> php_value auto_prepend_file "/user_name/public_html/phpmussel/loader.php"

**Comment by wajdijurry** [comment] 2017-03-30 23:00
Same problem friend, it is not scanning any file. It return "No problems found" for infected file !!!

**Comment by wajdijurry** [comment] 2017-03-30 23:04
I tried auto prepend method, but for nothing positive!!

**Comment by Maikuolan** [comment] 2017-03-30 23:07
Which version of the codebase are you using (e.g., from which version or commit did you install)?

As of https://github.com/Maikuolan/phpMussel/commit/5a93b4f44d9dbd22d99a37e6ac13dbd5e30a01d2 (committed 7 days ago / 2017.03.24), all the signature files were migrated from this repository to a separate repository of their own (i.e., there aren't any signature files included in this repository currently). If you're using a version of the codebase from within the past 7 days, that might possibly be the cause of the problem here. Although already mentioned in the changelog file, we haven't had time to update the main README documentation to reflect this change yet, unfortunately. If that's the case, let us know and I'll mention the additional required steps here (of course, we'll eventually add this information the READMEs as well, but it isn't there yet).

**Comment by DanielRuf** [comment] 2017-03-30 23:25
Please try one of the latest releases.

https://github.com/Maikuolan/phpMussel/releases

The message `No problems found` is a bit helpful. More helpful is how and when you've downloaded phpMussel (composer and the master branch?).

**Comment by wajdijurry** [comment] 2017-03-31 11:56
It worked when I downloaded the version 0.10.0, all signatures are included in the "signatures" folder, but the version I downloaded from this link https://github.com/Maikuolan/phpMussel does not include any signature file.

**Comment by DanielRuf** [comment] 2017-03-31 12:15
> It worked when I downloaded the version 0.10.0, all signatures are included in the "signatures" folder, but the version I downloaded from this link https://github.com/Maikuolan/phpMussel does not include any signature file.

Right. This is because this is the bleeding edge master version which includes the latest changes. Always use the releases. Composer and other package managers should install one of the releases by default and users should never download and install the development version in the master branch ;-)

https://github.com/Maikuolan/phpMussel/issues/126#issuecomment-290570211

Thanks for your feedback that the issue is solved.

**Closed as completed by DanielRuf** 2017-03-31 12:15 UTC
Labels: Support, Resolved
