### ISSUE TITLE
VirusTotal configuration

### ISSUE THREAD

**Issue by msouzarunner** [phpMussel/phpMussel#96] opened 2016-06-16 15:42 UTC
Hello, Maikuolan.

      I include my key in VirusTotal "vt_public_api_key" and changed the parameter "vt_suspicion_level = 2", but still does not trigger a scan on VirusTotal. What am I doing wrong ?

**Comment by Maikuolan** [comment] 2016-06-16 16:58
Hello msouzarunner,

I haven't encountered any problems like this in the past, but it definitely does sound unusual.

I'm currently replying from my workplace (no access to PHP, any of my working files, test tools, etc; limited terminal access), but I'll investigate this further as soon as I finish my shift (about 6 hours from now) and reply with whatever I can find.

**Comment by msouzarunner** [comment] 2016-06-16 17:09
Hello, Maikuolan.

```
I'm waiting.
```

**Comment by DanielRuf** [comment] 2016-06-16 20:17
@msouzarunner Was the same file upload scanned with phpMussel  before you added your VirusTotal API key?

Do you see any errors in the errorlog file of your server?

**Comment by Maikuolan** [comment] 2016-06-17 06:17
Finished work for the night and I've experimented a little with this.

> @msouzarunner Was the same file upload scanned with phpMussel  before you added your VirusTotal API key?

This is a possible cause of the problem here. If phpMussel scanned the file previously and marked it as benign, there would be an entry created in the phpMussel cache corresponding to this file, which phpMussel would then use instead of scanning it again if it encountered the same file again before the cache entry could be deleted (cache entries, by default, last 6 hours; however, this can be adjusted by using the `scan_cache_expiry` directive.

``` INI
; For how long should phpMussel cache the results of scanning? Value is the
; number of seconds to cache the results of scanning for. Default is 21600
; seconds (6 hours); A value of 0 will disable caching the results of scanning.
scan_cache_expiry=21600
```

Another way, too, that you can confirm whether phpMussel is attempting to communicate with the VirusTotal API, is that whenever phpMussel does this, a file will normally be created in the cache directory named "`76.tmp`" (path as `%phpMussel%/vault/cache/76.tmp`, and assuming that caching is enabled; of course, this won't occur if caching is disabled). The presence/absence of this file isn't conclusive to whether phpMussel is attempting to communicate with the VirusTotal API, but it's a reasonably reliable indicator (and so, if caching and lookups to the VirusTotal API are both enabled, and if this file doesn't appear after attempting to scan something, it could indicate some type of problem).

Likewise, when _any_ type of scanning is performed by phpMussel, a file should normally be created in the cache directory named "`48.tmp`" (assuming, again, that caching is enabled, and this won't occur if it's disabled).

For testing purposes, if caching is causing the problem, it's safe to simply delete these cache files; If you delete them, that simply means that phpMussel will think that it hasn't scanned any files before, and so it will attempt to scan them again when it encounters them, regardless of whether it's for the first time or otherwise.

**Comment by msouzarunner** [comment] 2016-06-17 09:51
Hello, Maikuolan.

The 76.tmp file is not being created. I deleted all the files in the cache folder and redid the process and again appears only the 48.tmp and index.dat files.

The parameter "scan_cache_expiry = 21600" is filled by default.

**Comment by msouzarunner** [comment] 2016-06-17 09:53
Hello, DanielRuf.

   I found no error in the log file.

**Comment by Maikuolan** [comment] 2016-06-18 17:01
Hm, interesting.

When the file was scanned, was it already flagged as malicious by phpMussel? Normally, if phpMussel doesn't detect anything wrong with the file by the time that it reaches the code for checking the file against the VirusTotal API, it will check it against the VirusTotal API (assuming this is enabled, of course), but if it has already detected something wrong with the file by the time that it reaches that part of the code, it will skip checking the VirusTotal API (because there won't be a need to check the VirusTotal API if the file is already known by phpMussel to be malicious).

(Ie, if it's already being flagged as malicious, there's no real problem here, but if it's getting past phpMussel without being flagged and _also_ not being checked against the VirusTotal API, then, something is definitely wrong, somewhere).

Aside from that.. Have there been any modifications to the phpMussel core?

**Comment by msouzarunner** [comment] 2016-06-19 08:24
Hello, Maikuolan.

I understand your statement, but I set the parameter "vt_suspicion_level = 2" so that even being declared supeito the file it is scanned by VirusTotal, that's right or get it wrong in the documentation?

**Comment by Maikuolan** [comment] 2016-06-19 09:43
The documentation _should_ be correct regarding this behaviour (relevant parts boldened/highlighted below); Improvements to the documentation are always welcomed, though (so, if there are any errors found, certainly, corrections are welcomed).

_[readme.en.md#virustotal-category](https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.en.md#virustotal-category):_

> 2: All files are considered suspicious and should be scanned using the Virus Total API. I don't generally recommend applying this suspicion level, due to the risk of reaching your API quota much quicker than would otherwise be the case, but there are certain circumstances (such as when the webmaster or hostmaster has very little faith or trust whatsoever in any of the uploaded content of their users) where this suspicion level could be appropriate. With this suspicion level, **all files not normally blocked or flagged as being malicious** would be scanned using the Virus Total API. Note, however, that phpMussel will cease using the Virus Total API when your API quota has been reached (regardless of suspicion level), and that your quota will likely be reached much faster when using this suspicion level.

_[readme.pt.md#virustotal-categoria](https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.pt.md#virustotal-categoria):_

> 2: Todos arquivos são considerados suspeitos e devem ser verificados usando o Virus Total API. Eu geralmente não recomendamos a aplicação desse nível de suspeita, devido ao risco de atingir sua API cota muito mais rápido do que de caso contrário seria o caso, mas existem certas circunstâncias (tal como quando o webmaster ou hostmaster tem muito pouca fé ou confiança em qualquer um dos conteúdos carregados por seus usuários) onde este nível suspeita pode ser adequado. Com este nível suspeita, **todos arquivos normalmente não bloqueados ou marcados como sendo malicioso** seria analisados usando o Virus Total API. Notar, porém, que phpMussel deixará usando o Virus Total API quando sua API cota foi atingido (independentemente do nível de suspeita), e que a sua cota será provavelmente ser alcançado muito mais rápido quando se usando este nível de suspeita.

That said, though, if it was desired for phpMussel to truly scan _all_ files - _regardless of whether they'd already been marked as malicious_ - the necessary modification to the core code is very small, and should be very easy to do.

Currently, in `functions.php`, at the beginning of the code block responsible for checking files against the VirusTotal API, there's this:

``` PHP
    /** Virus Total API integration. */
    if (
        !$out &&
        !empty($phpMussel['Config']['virustotal']['vt_public_api_key'])
    ) {
        $DoScan = false;
        $phpMussel['Config']['virustotal']['vt_suspicion_level'] =
            (int)$phpMussel['Config']['virustotal']['vt_suspicion_level'];
// (snip) the remainder of the relevant code after this line...
```

If we knocked out the `!$out &&` line from that code (so that it would look like this):

``` PHP
    /** Virus Total API integration. */
    if (
        !empty($phpMussel['Config']['virustotal']['vt_public_api_key'])
    ) {
        $DoScan = false;
        $phpMussel['Config']['virustotal']['vt_suspicion_level'] =
            (int)$phpMussel['Config']['virustotal']['vt_suspicion_level'];
// (snip) the remainder of the relevant code after this line...
```

..that would cause phpMussel to check everything against the VirusTotal API, regardless of whatever else had already been detected.

The reason for this condition to prevent phpMussel from checking files against the VirusTotal API when a file has already been flagged as malicious, is to protect a user's API quota from easily going over the limit (doing the minimal required work, and no extra, should conserve resources). Though, if you've got a larger quota, and if you're not too concerned about exceeding it, it should be safe to knock out that line and allow phpMussel to check already flagged files.

(Of course, cached scan results will continue to be used in favour of checking the same files multiple times; Disabling caching will allow the same files to be checked multiple times, but, the risk in doing this is that an attacker could flood the same files hundreds, thousands of times to the server, in order to intentionally wipe out quotas; In theory, for example, a random dummy text file could be sent an adequate number of times for wiping out a quota, prior to sending a malicious file, in order to prevent malicious files from being detected, due to quotas being exceeded prior to malicious files being uploaded; Because of this, I would recommend to not disable the cache).

**Comment by DanielRuf** [comment] 2016-06-19 13:58
@msouzarunner and error_reporting is enabled and display_errors is used for debugging?

We have to reproduce this issue somehow. can you provide some details about the scanned file?

Does phpMussel successfully detect the example files? Are cache files created (if not check the errorlog of your server and the chmod rights)?

**Comment by msouzarunner** [comment] 2016-06-20 08:45
Hello, Maikuolan.

   I understood how to scan using VirusTotal API from phpMussel. My intention is not to use this way in production, but wanted to see the use of VirusTotal API and its return.

    I appreciate the change in the code so that I can have this result, but in no way will implement it permanently.

**Comment by Maikuolan** [comment] 2016-06-20 08:58
:+1: 

No worries, happy to help. :-)

I'll mark this issue as "resolved" and close it for now; If there are any more problems, feel free to re-open it or create new issues.

**Comment by msouzarunner** [comment] 2016-06-20 08:59
Hello, DanielRuf.

Yes, error_reporting and display_errors is enabled as well.

I'm using eicar.com.txt file.

Yes, phpMussel detects the virus in the file.

Yes, they are generated 48.tmp and index.dat files.

I checked erro.log and nothing appears wrong.

The permissions are 775.

**Closed as completed by Maikuolan** 2016-06-20 08:58 UTC
Labels: Support, Resolved
