### ISSUE TITLE
Unauthorised file upload manipulation detected

### ISSUE THREAD

**Issue by gunarecro** [phpMussel/phpMussel#191] opened 2019-02-25 16:17 UTC
### Operating system used Windows NT INFO952 10.0 build 17134 (Windows 10) i586

---
## Issue
This is my localhost
I'm getting the following error

Router:

```
$app->post('/scan', function ($request, $response, $args) {

		$pdata 		= $request->getParsedBody ();
		$fdata   	= $request->getUploadedFiles();
		$filename   = $fdata ['file']->getClientFilename();
		$uploadDir  =  ROOT . DIRECTORY_SEPARATOR . $filename;
		// echo $uploadDir;exit;
		$result 	= $fdata ['file']->moveTo($uploadDir);

		$scan 		= new scan ();
		$uploadDir  = '';
		$scanResult = $scan->scanFile ($uploadDir);

		print_r($scanResult);exit;
	});
```

```
class scan {    

        public function scanFile ($filePath) {

            require ROOT . '/api-virus/vendor/phpmussel/phpmussel/loader.php';
            
            $results = $phpMussel['Scan']($filePath, true, true);
            return $results;
        }
    } // Class End
```

`<div id="results"><div id="denied">Upload Denied!</div><div id="denied_reason">Your upload was blocked for the reasons listed below:</div></div><div id="detected">Unauthorised file upload manipulation detected (CP014-CDMS-HT-18-EA106-1.0-007_EJ02.pdf)!</div><hr /><div id="footer"><div id="footer_inner"><div id="generated_by">Generated by </div><div id="phpmusselversion">phpMussel v1.8.0</div></div>`

### Expected behavior
It's should give the string or integer value 

Thanks,
Guna.

**Comment by Maikuolan** [comment] 2019-02-26 00:35
The "Unauthorised file upload manipulation detected (xxx)!" message that we see here, is generated specifically by the "upload handler", rather than by the core scan functionality itself.

Your class and related code looks okay, and I don't think is causing any problem here, nor necessarily the phpMussel core itself. Rather, what I think is happening is that the upload handler is trying to initiate a scan event (as part of the upload scanning behaviour bundled into phpMussel by default), generating that message, and then dieing the request, before your class and related code has a chance to execute in the first place.

I plan to implement a better solution in a future version (v2), but for the moment (i.e., for currently available versions and releases), to resolve the problem, try to delete or rename the `upload.php` file in the vault to something else. The `upload.php` file is responsible for the default upload scanning behaviour in phpMussel, and responsible for initiating these default scan events, but doesn't actually contain anything belonging to the phpMussel core (e.g., phpMussel's internal closures, classes, etc). Because phpMussel is designed to be "modular", deleting or renaming `upload.php` won't break anything in phpMussel or prevent anything from working, other than its default upload scanning behaviour (which probably isn't needed here anyway, seeing as you've written your own class to handle this). When phpMussel looks for `upload.php`, if it finds it, it'll try to load it; if it doesn't find it, it'll just skip over it and continue with the request, without generating any errors, warnings, notices, etc.

Let me know how it goes. :-)

**Comment by gunarecro** [comment] 2019-02-26 04:57
Hey Maikuolan,

Thank you  for your valuable reply. Its working fine now. 
After rename the `upload.php` inside the **vault** folder.

## Server information. 

### phpMussel version used v1.8.0
### PHP SAPI used cgi-fcgi
### PHP version installed 5.6.39
### Operating system used Linux 4.14.77-70.82.amzn1.x86_64 #1 SMP Mon Dec 3 20:01:27 UTC 2018 x86_64

I'm facing one more problem. Whenever i will login in the **FRONT-END MANAGEMENT**  first time its allowing me to login after that if i click any links in the menu or on that page it's again redirect me to login page.

Could please tell me what is the problem but it's working in **localhost** but not working in AWS test server.

Thanks,
Guna

**Comment by Maikuolan** [comment] 2019-03-01 15:05
> I'm facing one more problem. Whenever i will login in the **FRONT-END MANAGEMENT**  first time its allowing me to login after that if i click any links in the menu or on that page it's again redirect me to login page.
>
> Could please tell me what is the problem but it's working in **localhost** but not working in AWS test server.

Does the vault directory for phpMussel on the AWS test server have appropriate write permissions set? It could be a permissions/CHMOD problem possibly.

**Comment by gunaerode** [comment] 2019-03-04 08:03
> Does the vault directory for phpMussel on the AWS test server have appropriate write permissions set? It could be a permissions/CHMOD problem possibly.

Yes i have given 0755 to vault folder.

**Comment by Maikuolan** [comment] 2019-03-05 07:37
I guess, probably not a permissions problem then. 0755 should be adequate permissions for phpMussel to be able to function correctly.

Some other possibilities:
- Do you have multiple phpMussel installations operating under the same domain name? If so, it's possible that the multiple installations are trying to use the same cookie, therefore invalidating each other's sessions whenever trying to log into the front-end (if so, we might need to perform some small modifications to the installations so that they can both work without invalidating each other's sessions).
- Do you have cookies disabled? If it's working on localhost, then I doubt that this is the cause of the problem (because it shouldn't work anywhere at all, if this was the cause of the problem), but I ask anyway, in order to cover all possibilities. Logging into the phpMussel front-end requires browser cookies to be enabled. Without cookies, it won't remember the session between requests, so we could expect it to redirect back to the login page again like that.
- When modifying/writing files to AWS, do you know whether the changes appear immediately, or whether there is some delay (e.g., whether the changes maybe need to propagate through multiple servers before they appear, or whether there is some kind of server-side caching mechanism preserving the previous state of the files for a while, before the changes take effect)? I'm thinking that if there's some kind of delay, propagation required before changes appear, or some kind of caching mechanism like that, then it's possible that that could be interfering with phpMussel's ability to remember sessions (because phpMussel currently uses a "flatfile" system to store its cache, login sessions, etc). I'm hoping that this isn't the cause of the problem, because of all the mentioned possibilities, this possibility would require the greatest amount of work to resolve.. but good to investigate all possibilities nonetheless.

**Comment by Maikuolan** [comment] 2019-03-17 09:28
*Marking as resolved and closing.*

**Closed as completed** 2019-03-17 09:28 UTC
Labels: Support, Resolved
