### ISSUE TITLE
some warnings produced when using phpMussel() and cache not filled

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#39] opened 2015-07-06 18:33 UTC
When I run this code (Windows 7, XAMPP Version: 5.6.3, Apache with increased stacksize - 8MB)

```
<?php
include 'phpmussel.php';
echo phpMussel("_testfiles/ascii_standard_testfile.txt");
```

I get these warnings:

```
Warning: preg_match(): \vault\phpmussel.inc on line 1030

Warning: preg_match(): Unknown modifier ')' in \vault\phpmussel.inc on line 1030

Warning: preg_match(): Unknown modifier ']' in \vault\phpmussel.inc on line 1030

Warning: preg_match(): Compilation failed: numbers out of order in {} quantifier at offset 197 in \vault\phpmussel.inc on line 6810

Warning: preg_match(): Compilation failed: numbers out of order in {} quantifier at offset 197 in \vault\phpmussel.inc on line 6810

Warning: preg_match(): Compilation failed: regular expression is too large at offset 286 in \vault\phpmussel.inc on line 6810

Warning: preg_match(): Compilation failed: regular expression is too large at offset 286 in \vault\phpmussel.inc on line 6810

Warning: preg_match(): Compilation failed: regular expression is too large at offset 132 in \vault\phpmussel.inc on line 6810

Warning: preg_match(): Compilation failed: regular expression is too large at offset 132 in \vault\phpmussel.inc on line 6810

2
```

At least these are just warnings and not critial errors, we can suppress this using `error_reporting(0);` and so on.

Increasing the PCRE values does not remove these warnings: http://stackoverflow.com/questions/8268624/php-preg-match-all-limit

**Comment by Maikuolan** [comment] 2015-07-06 19:58
Hmm, I suspect this may be a problem with some of the signatures. I'll do some digging to try to work out exactly where the problem is. Thanks for spotting.

**Comment by Maikuolan** [comment] 2015-07-10 13:41
I did find a small problem in the code I'd written for adapting the signatures from the ClamAV database for use in phpMussel that could've potentially affected some of the HTML and ASCII signatures; I haven't yet fixed this problem, but, I've generated a new set of signatures that omits any of the signatures that I thought could've potentially been affected.

To confirm if this problem was the cause of the warnings, could you run that test again with the updated signatures?

**Comment by DanielRuf** [comment] 2015-07-10 14:23
Much better, the warnings are gone now. Just these 3 are left:

```
Warning: preg_match(): Unknown modifier 'p' in vault\phpmussel.inc on line 1031
Warning: preg_match(): Unknown modifier ')' in vault\phpmussel.inc on line 1031
Warning: preg_match(): Unknown modifier ']' in vault\phpmussel.inc on line 1031
```

I tried some solutions like `#` but did not find a final solution.

Does it make sense to add an option to use the cache in combination with `cleanup=0` to speed up local file scans?

**Comment by Maikuolan** [comment] 2015-07-10 22:11
The cache data should only be discarded when the request has terminated or when `cleanup=1`, and so, when everything is working correctly, the cache should work in combination with `cleanup=0`, anyhow (assuming I'm understanding correctly).

Currently, the cache should always be active (except for when everything is unloaded/unset because of `cleanup=1`), because I haven't added any directives to disable it, so, that's possibly something to be added in; Is that what you meant?

Also, thanks for re-testing. :-)

I found some weird regex stuff in the ClamAV filename signatures that didn't look correct, so, I suspect that may be causing those last 3 warnings; I've made some changes to them and will re-commit soon, hopefully getting rid of those last 3 warnings (also making some others changes to the code; mentioning `cleanup` has made me think on potential use a little, and I'm adding some additional safeguards for it that hopefully should help a little; I should have that done in an hour or so; also adding some new language variables that will need translating when it's committed; I'll reference this issue when it's committed).

**Comment by DanielRuf** [comment] 2015-07-11 08:42
At least I see no generated files when cleanup is set to 0 and I run the manual scan with phpMussel().

Is the cache in this mode on Windows in tmp or so? I have to check this after cleaning all local caches.

Thanks, I will translate the new strings today.

**Comment by DanielRuf** [comment] 2015-07-11 12:00
The warnings are gone now. 

When I scan a clean file, I get these notices:

```
Notice: Undefined variable: str in C:\xampp\htdocs\phpMussel-master\phpMussel-master\vault\phpmussel.inc on line 13587

Notice: Undefined variable: str_hex in C:\xampp\htdocs\phpMussel-master\phpMussel-master\vault\phpmussel.inc on line 13587
1
```

But the cache is still not filled when manually using `phpMussel()`

Tested this with 05ee21f48a2ab37de672f06f3a1f30d8f226b230

I wonder if it would be possible and senseful to be able to use phpMussel() for uploads and also call `phpMussel()` manually like in the testscript from me or does the user need two phpMussel setups with different configurations? Does it make sense to support multiple configurations (which can be also set as parameter in `phpMussel()` when manually called or so) per phpMussel setup (eg if we have a server with multiple websites like a multisite in WordPress or something other, subdomains, different directories, landing pages, ...) in the future?

**Comment by Maikuolan** [comment] 2015-07-11 17:42
> Is the cache in this mode on Windows in tmp or so? I have to check this after cleaning all local caches.

Cache data for phpMussel should all be stored in `%phpmussel%/vault/cache/*`. :-)

> When I scan a clean file, I get these notices:
> `(snip)`

Oops.. Those particular lines are placeholders for where future RAR code should eventually go; Nothing critical (because the RAR code for phpMussel hasn't been written yet), but, I used some variables there for the placeholders that belong to a different function, instead of the variables that I should've used; My bad. I'll commit a fix for that shortly. ^_^

> But the cache is still not filled when manually using `phpMussel()`

Very strange. :-/

Not sure what's causing that yet, but, I'll do some testing on my end tonight to try to work it out.

> I wonder if it would be possible and senseful to be able to use phpMussel() for uploads and also call `phpMussel()` manually like in the testscript from me or does the user need two phpMussel setups with different configurations? Does it make sense to support multiple configurations (which can be also set as parameter in `phpMussel()` when manually called or so) per phpMussel setup (eg if we have a server with multiple websites like a multisite in WordPress or something other, subdomains, different directories, landing pages, ...) in the future?

It -should- work with one setup, but, in case there are problems (or for cases where maybe we want different configurations for different situations), allowing multiple configurations might be a good idea; The big question, of course, would be how to implement it in a standardised way; At the moment, I'm not entirely sure how, but, it's something to think about, anyhow.

**Comment by Maikuolan** [comment] 2015-07-11 21:34
> Not sure what's causing that yet, but, I'll do some testing on my end tonight to try to work it out.

Found the source of the problem; Working on a fix now.

**Comment by DanielRuf** [comment] 2015-07-11 21:55
> > Not sure what's causing that yet, but, I'll do some testing on my end tonight to try to work it out.
> 
> Found the source of the problem; Working on a fix now.

Great =)

I have to study the complete sourcecode (which is quite much) when I have the time (appreciate your great work, phpMussel is a very mighty and effective solution).

**Comment by Maikuolan** [comment] 2015-07-11 22:40
Committed, and glad to hear it's working well. :-)

**Comment by DanielRuf** [comment] 2015-07-11 22:58
Ok, notices are gone and the results are now:

Elapsed time was 0.492506980896 seconds. (first scan / before)
Elapsed time was 0.027499914169312 seconds. (further scans / after)

I think the issue can be closed now. =)

I used this code for measuring the runtime: http://psoug.org/snippet/Measure-script-run-time_919.htm

**Comment by Maikuolan** [comment] 2015-07-12 00:52
Awesome! :-)

At some point in the future I'll still need to fix the code that I'm using to adapt signatures from the ClamAV database for usability in phpMussel, but because the code in question is only for adapting signatures and isn't present in phpMussel itself, the problem shouldn't be evident in or be affecting the next release.

Anyhow, closing this issue now.

**Closed as completed by Maikuolan** 2015-07-12 00:52 UTC
Labels: Bug, Fixed
