### ISSUE TITLE
inconsistent return values for phpMussel()

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#44] opened 2015-07-12 15:33 UTC
Shouldn't this output the same like the code below?

```
echo phpMussel("_testfiles/ascii_standard_testfile.txt",2);
Sun, 12 Jul 2015 17:25:49 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> No problems found. Sun, 12 Jul 2015 17:25:49 +0200 Finished.
```

```
echo phpMussel("_testfiles/ascii_standard_testfile.txt",1);
Sun, 12 Jul 2015 17:26:46 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> Detected phpMussel-FN.Illegal.Character-2F! -> Detected phpMussel-Testfile.ASCII.Standard! Sun, 12 Jul 2015 17:26:46 +0200 Finished.
```

**Comment by Maikuolan** [comment] 2015-07-12 15:39
Yeah, the output should be the same; Looks like another bug, I think. I'll take a look at this over the weekend. Thanks for spotting.

**Comment by Maikuolan** [comment] 2015-07-14 08:36
I think I might've determined the cause of this bug: Between two consecutive scans using both possible values of `$output_type`, depending on which `$output_type` is used first, the scan results seem to be cached slightly differently; In one case, the secondary scan will think there aren't any problems, but in the other case, it seems to work correctly. The reason it's cached differently is because the generated data is slightly different, and the cache system is just caching whatever data is generated, but then when that data is recalled using a different value for `$output_type`, the data being retrieved will be for the original `$output_type` used, and so, will be inappropriate for the newly given `$output_type`.

I have some ideas on ways to fix this, but I'm not 100% certain about their viability; I'll do some experimenting later today.

**Comment by DanielRuf** [comment] 2015-07-14 11:32
Ok, good that we found the bug. Let me know when there is a commit which fixes this so I can run some more tests with different values.

**Comment by Maikuolan** [comment] 2015-07-14 21:18
Committed. Let me know how it goes. :-)

**Comment by DanielRuf** [comment] 2015-07-15 07:44
Works now like desired.

When I use `echo phpMussel("_testfiles/ascii_standard_testfile.txt",1);` I get these notices

```
Notice: Undefined variable: memCache in vault\phpmussel.inc on line 896
Notice: Undefined variable: memCache in vault\phpmussel.inc on line 906
```

I think instead of  `$memCache['eof']` this should be `$GLOBALS['memCache']['eof']`

I will rerun the other tests this week (I think I will create some test plan with all tests).

**Comment by Maikuolan** [comment] 2015-07-15 10:06
Yeah, it should; Good spotting. XD

Fixed; Recommitting it now.

**Comment by DanielRuf** [comment] 2015-07-17 09:14
Where does the `Detected phpMussel-FN.Illegal.Character-2F!` come from?

Because under some circumstances it is not in the result

```
Fri, 17 Jul 2015 11:03:31 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> Detected phpMussel-FN.Illegal.Character-2F! -> Detected phpMussel-Testfile.ASCII.Standard! Fri, 17 Jul 2015 11:03:33 +0200 Finished. 
Fri, 17 Jul 2015 11:03:33 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> Detected phpMussel-FN.Illegal.Character-2F! -> Detected phpMussel-Testfile.ASCII.Standard! Fri, 17 Jul 2015 11:03:33 +0200 Finished.

Fri, 17 Jul 2015 11:05:18 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> Detected phpMussel-Testfile.ASCII.Standard! Fri, 17 Jul 2015 11:05:18 +0200 Finished. 
Fri, 17 Jul 2015 11:05:18 +0200 Started. > Checking '_testfiles/ascii_standard_testfile.txt' (FN: b492df2f; FD: c4f668fa): -> Detected phpMussel-Testfile.ASCII.Standard! Fri, 17 Jul 2015 11:05:18 +0200 Finished.
```

It seems this is fixed in the latest version.

**Comment by Maikuolan** [comment] 2015-07-17 18:57
That was a bug; It should've (hopefully) been fixed as of the latest commit. One of the conditions checks in place in the `filenames_mussel.cvd` file wasn't correct.

[Before](https://github.com/Maikuolan/phpMussel/blob/3ab6285dc2657ab9167bf58186e2d9924c9d5411/vault/filenames_mussel.cvd#L426):

> `>$climode>0>464`

[After](https://github.com/Maikuolan/phpMussel/blob/master/vault/filenames_mussel.cvd#L426):

> `>!$climode>1>464`

In short.. phpMussel thought that the directory separator was a part of the filename, and because slashes shouldn't be in filenames, it flagged the file as having an "illegal character". The condition check (when working correctly and not bugged) tells it to ignore those signatures when scanning in CLI mode.

**Comment by Maikuolan** [comment] 2015-07-17 19:00
For some reason, the condition check wouldn't work correctly when I used `$Var==0`, but it seemed to work when I used `$Var!=1`. I suspect it might be a typecasting problem due to the way I'd coded condition checks in signature files to work (I'll need to look into that at some point), but, seeing as `$Var!=1` seemed to work anyhow, for now, I just changed it to that.

**Comment by DanielRuf** [comment] 2015-07-17 20:28
Ok, seems fixed and can be closed in my opinion.

Was not quite clear that `[2015.07.15; Bug-fix;
Maikuolan]: Found and fixed a bug whereby scanning individual files in
CLI mode under Windows would sometimes produce a false positive as a
result of the format of the directory tree.` addressed this :D

Sorry, but good that we have both found this issue. I was just a bit slow and may have seen it before :D 

It seems it was alreade here in my first comment of this issue and I just oversaw this as a second bug: https://github.com/Maikuolan/phpMussel/issues/44#issue-94573908

**Comment by Maikuolan** [comment] 2015-07-17 21:02
> It seems it was already here in my first comment of this issue and I just oversaw this as a second bug

No worries; S'all good. That first comment is actually how I found it; I saw the detection there, and thought, that detection there doesn't look correct, and so, investigated it at the same time as fixing the other problem. ^.^

Closing now.

**Closed as completed by Maikuolan** 2015-07-17 21:02 UTC
Labels: Bug, Fixed
